# Generated by Django 5.2.9 on 2026-09-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session_version",
            field=models.PositiveIntegerField(default=1, verbose_name="会话版本"),
        ),
    ]
