# Generated by Django 5.2.9 on 2026-09-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_seed_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ban_reason",
            field=models.CharField(blank=True, max_length=200, verbose_name="封禁原因"),
        ),
    ]
